### PR TITLE
bring back dataframe with a bump

### PR DESCRIPTION
**Pull request by juhp**
`dataframe-0.2` [fell out](https://github.com/commercialhaskell/lts-haskell/commit/52da9b14e46d588b9856625a0f7f751c059bab27) of lts-24 when we moved to 9.10.3 (due to its `text` bump) - this brings back `dataframe-0.3`.

The version bump might not be ideal, but I still feel better than not shipping it at all.

Checklist for adding a package:
- [x] Meaningful commit message, eg `add my-cool-package` (please don't mention the yaml file)
- [x] Package is already added to nightly (if possible)
- [ ] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

or using the [verify-package script](https://github.com/commercialhaskell/stackage/blob/master/verify-package):

      verify-package $package lts

_(seems a bug that github renders this with so much vertical space?)_

### CODE REVIEW

**Comment by juhp** [comment]
Though if we are bumping the version in LTS anyway - it might make better sense to just go to a higher version of dataframe perhaps? 0.7 (down to 0.5) all seem to build with ghc-9.10.3, but not 1.x.

(Normally we prefer not to bump major version of course, that would require a revision of 0.2) 

cc @mchav

**Comment by juhp** [comment]
Unfortunately dataframe-0.3.4.1 failed to build:

```
       /home/curators/work/unpack-dir/unpacked/dataframe-0.3.4.1-10e1b8f9e797c844024cca7da03f09be0d5bda7b6e5c8970f08b45a2a098dd1f/src/DataFrame/Operations/Permutation.hs:68:47: error: [GHC-88464]
           Variable not in scope:
             uniformShuffleList :: [Int] -> g -> ([Int], b0)
          |
       68 | shuffledIndices pureGen k = VU.fromList (fst (uniformShuffleList [0 .. (k - 1)] pureGen))
          |                                               ^^^^^^^^^^^^^^^^^^
```
